### ISSUE TITLE
Add Python3.10 template flavor

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#864]
In https://github.com/exasol/script-languages-release/issues/849, we created a prototype for a Python 3.10 container. We now need to make production ready.

```[tasklist]
### Tasks
- [x] Set derived from
- [x] Add flavor documentation
- [x] Update packages
- [x] Generate package diff
- [ ] https://github.com/exasol/script-languages-release/issues/863
- [x] Update buildspec
```
